# Generated by Django 2.0.5 on 2018-05-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=100)),
                ('nombre_apellidos', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=80)),
            ],
        ),
    ]
